server:
  port: ${port:9091}
spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud
    username: root
    password: 1466045175

mybatis:
  type-aliases-package: com.lxs.user.pojo
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10085/eureka
  instance:
    ## ip地址
    prefer-ip-address: true
    ip-address: 127.0.0.1
    #续约时间间隔，默认30秒
    lease-renewal-interval-in-seconds: 5
    #服务失效时间，默认90秒
    lease-expiration-duration-in-seconds: 5
